from pygments.lexer import RegexLexer, bygroups, words
from pygments.token import (
    Comment,
    Keyword,
    Name,
    Number,
    Operator,
    Punctuation,
    String,
    Text,
)


class ZerionyxLexer(RegexLexer):
    name = "Zerionyx"
    aliases = ["zerionyx", "zyx"]
    filenames = ["*.zyx", "*.zex"]

    zyx_keywords = (
        "and",
        "or",
        "not",
        "if",
        "elif",
        "else",
        "for",
        "to",
        "do",
        "step",
        "while",
        "defun",
        "done",
        "return",
        "continue",
        "break",
        "load",
        "in",
        "del",
        "namespace",
        "using",
        "parent",
    )

    zyx_constants = ("true", "false", "none", "PI", "E", "ln2", "nan", "inf", "neg_inf")

    zyx_builtins = (
        "println",
        "print",
        "input",
        "get_password",
        "clear",
        "type",
        "is_none",
        "is_num",
        "is_bool",
        "is_str",
        "is_list",
        "is_func",
        "is_thread",
        "is_thread_pool",
        "is_future",
        "is_namespace",
        "is_channel",
        "is_cfloat",
        "is_py_obj",
        "is_nan",
        "is_panic",
        "len",
        "panic",
        "pop",
        "append",
        "insert",
        "extend",
        "slice",
        "to_str",
        "to_int",
        "to_float",
        "to_cfloat",
        "to_bytes",
        "pyexec",
        "clone",
        "keys",
        "values",
        "items",
        "has",
        "get",
        "del_key",
        "get_member",
        "shl",
        "shr",
        "bitwise_and",
        "bitwise_or",
        "bitwise_xor",
        "bitwise_not",
    )

    zyx_types = (
        "list",
        "str",
        "int",
        "float",
        "func",
        "bool",
        "hashmap",
        "thread",
        "bytes",
        "py_obj",
        "cfloat",
        "namespace",
        "channel_type",
        "thread_pool_type",
        "future_type",
        "none_type",
    )

    tokens = {
        "root": [
            (r"\s+", Text),
            (r"#.*$", Comment.Single),
            (r"&[a-zA-Z_]\w*(?:\.[a-zA-Z_]\w*)*", Name.Decorator),
            (r"(defun)(\s+)([a-zA-Z_]\w*)", bygroups(Keyword, Text, Name.Function)),
            (
                r"(namespace)(\s+)([a-zA-Z_]\w*)",
                bygroups(Keyword.Namespace, Text, Name.Namespace),
            ),
            (r"(load)(\s+)", bygroups(Keyword.Namespace, Text), "load_string"),
            (words(zyx_keywords, suffix=r"\b"), Keyword),
            (words(zyx_constants, suffix=r"\b"), Keyword.Constant),
            (words(zyx_builtins, suffix=r"\b"), Name.Builtin),
            (words(zyx_types, suffix=r"\b"), Name.Builtin.Pseudo),
            (r'"""', String.Double, "string_double_multiline"),
            (r"'''", String.Single, "string_single_multiline"),
            (r'"', String.Double, "string_double"),
            (r"'", String.Single, "string_single"),
            (r"\d+\.\d+", Number.Float),
            (r"\d+", Number.Integer),
            (
                r"(\+=|-=|\*=|/=|//=|%=|\^=|==|!=|<=|>=|<|>|\+|-|\*|//|/|%|\^|\$|=)",
                Operator,
            ),
            (r"[.,:;(){}\[\]\\]", Punctuation),
            (r"[a-zA-Z_]\w*", Name),
        ],
        "load_string": [
            (r'"[^"]*"', String.Double, "#pop"),
            (r"'[^']*'", String.Single, "#pop"),
            (r"\s+", Text),
            (r"", Text, "#pop"),
        ],
        "string_double_multiline": [
            (r'[^"\\]+', String.Double),
            (r"\\.", String.Escape),
            (r'"""', String.Double, "#pop"),
            (r'"', String.Double),
        ],
        "string_single_multiline": [
            (r"[^'\\]+", String.Single),
            (r"\\.", String.Escape),
            (r"'''", String.Single, "#pop"),
            (r"'", String.Single),
        ],
        "string_double": [
            (r'[^"\\]+', String.Double),
            (r"\\.", String.Escape),
            (r'"', String.Double, "#pop"),
        ],
        "string_single": [
            (r"[^'\\]+", String.Single),
            (r"\\.", String.Escape),
            (r"'", String.Single, "#pop"),
        ],
    }
